#!/bin/bash

st=$(($(date +%s%N)/1000000))

OMPI_MCA_mpi_warn_on_fork=0
export OMPI_MCA_mpi_warn_on_fork
#OMPI_MCA_oob_tcp_if_include=ib0
#export OMPI_MCA_oob_tcp_if_include

python $vivaldi_path/src/interactive_mode/main.py $@
#python $vivaldi_path/src/interactive_mode/testspawn.py $@
#mpirun --mca oob_tcp_if_include ib0 -np 1 python $vivaldi_path/src/interactive_mode/main.py $@

end=$(($(date +%s%N)/1000000))
duration=$((end-st))

echo "Vivaldi execution time:" $duration "msec"
